# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - about.md
 - running.md
 - resume.md
footer: '<a href = "mailto: hraizes99@gmail.com">Email</a> | <a href="https://www.linkedin.com/in/hraizes/">LinkedIn</a> | <a href="https://github.com/hraizes">GitHub</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  
theme: jekyll-theme-console
